// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {models} from '../models';
import {processutils} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {service} from '../models';

export function AddGameFromWebMetadata(arg1:vo.GameMetadataFromWebVO):Promise<void>;

export function BatchUpdateStatus(arg1:Array<string>,arg2:string):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function DeleteGames(arg1:Array<string>):Promise<void>;

export function DownloadCoverImage(arg1:string,arg2:string):Promise<string>;

export function ExportLaunchShortcut(arg1:string):Promise<string>;

export function FetchMetadata(arg1:vo.MetadataRequest):Promise<models.Game>;

export function FetchMetadataByName(arg1:string):Promise<Array<vo.GameMetadataFromWebVO>>;

export function FetchMetadataFromWeb(arg1:vo.MetadataRequest):Promise<vo.GameMetadataFromWebVO>;

export function GetGameByID(arg1:string):Promise<models.Game>;

export function GetGames(arg1:vo.GameListRequest):Promise<vo.GameListResponse>;

export function GetRunningProcesses():Promise<Array<processutils.ProcessInfo>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function OpenLocalPath(arg1:string):Promise<void>;

export function RefreshAllGamesMetadata():Promise<vo.MetadataRefreshResult>;

export function RefreshGamesMetadata(arg1:Array<string>):Promise<vo.MetadataRefreshResult>;

export function ResolveExecutablePathForImport(arg1:string):Promise<string>;

export function SaveCoverImageDataURL(arg1:string,arg2:string):Promise<string>;

export function SelectCoverImage(arg1:string):Promise<string>;

export function SelectCoverImageWithTempID():Promise<string>;

export function SelectGameExecutable(arg1:string):Promise<string>;

export function SelectSaveDirectory():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function SetBangumiService(arg1:service.BangumiService):Promise<void>;

export function SetEventEmitter(arg1:any):Promise<void>;

export function SetImageDownloadTaskStarter(arg1:any):Promise<void>;

export function SetTagService(arg1:service.TagService):Promise<void>;

export function UpdateGame(arg1:models.Game):Promise<void>;

export function UpdateGameFromRemote(arg1:string):Promise<void>;

export function UpdateGameProcessName(arg1:string,arg2:string):Promise<void>;
