// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUserTag(arg1, arg2) {
  return window['go']['service']['TagService']['AddUserTag'](arg1, arg2);
}

export function DeleteTag(arg1) {
  return window['go']['service']['TagService']['DeleteTag'](arg1);
}

export function FilterExistingTagNames(arg1) {
  return window['go']['service']['TagService']['FilterExistingTagNames'](arg1);
}

export function GetGameIDsByTag(arg1) {
  return window['go']['service']['TagService']['GetGameIDsByTag'](arg1);
}

export function GetTagsByGame(arg1) {
  return window['go']['service']['TagService']['GetTagsByGame'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['TagService']['Init'](arg1, arg2, arg3);
}

export function SearchTagsInLibrary(arg1) {
  return window['go']['service']['TagService']['SearchTagsInLibrary'](arg1);
}
