// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function AddUserTag(arg1:string,arg2:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function FilterExistingTagNames(arg1:Array<string>):Promise<Array<string>>;

export function GetGameIDsByTag(arg1:string):Promise<Array<string>>;

export function GetTagsByGame(arg1:string):Promise<Array<models.GameTag>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function SearchTagsInLibrary(arg1:string):Promise<Array<string>>;
